export const CATEGORIES = [
  ".cursorrules",
  // "Angular",
  "Anthropic(Claude)",
  // "AutoHotkey",
  // "Backend",
  "Bolt.new",
  // "C#",
  // "C++",
  "ChatGPT",
  "Chef",
  // "Codeium",
  "Convex",
  // "Creatr",
  "Cursor",
  // "Database",
  // "Deepseek",
  "Devin",
  // "Django",
  // "Expo",
  // "Express.js",
  // "Flutter",
  // "Functional",
  "Github Gopilot",
  // "Go",
  // "Guidelines Doc",
  // "HTMX",
  //"JavaScript",
  //"Jest",
  // "Laravel",
  "Loveable",
  // "MagicUI",
  // "MCP",
  "NextJS",
  // "Novo Elements",
  // "NuxtJS",
  "Openai",
  "Other",
  "Perplexity",
  "Prompt",
  //  "Python",
  // "Radix UI",
  "React",
  "Readme",
  // "Replit",
  // "Requirements Doc",
  // "Ruby on Rails",
  // "Rust",
  // "Shadcn UI",
  // "ShipFast",
  // "Solidity",
  // "Structure Doc",
  // "Supabase",
  // "SvelteKit",
  // "SwiftUI",
  // "TabNine",
  // "Tailwind",
  // "TanStack",
  // "trae",
  // "Trickle",
  "Typescript",
  "v0",
  //"Vue",
  //"Wails.io",
  "Windsurf",
  "YouTube",
] as const;
